### PR TITLE
Allow arbitrary (string) decoy keys to be passed to `requestDOMPermit`

### PR DESCRIPTION
**Pull request by colingourlay**
Currently, News Web provides 3 decoy components for us to activate before tampering with the Presentation Layer DOM, each with one of the following activation listen keys:

- `article`,
- `body`, &
- `page`

Because of this, we'd assumed for this library that when calling `requestDOMPermit`:

1. We needed to supply one of those three strings as the `key` argument, and
2. Each would request would result in the activation of only one DOM node.

It turns out that the latter assumption was wrong (multiple decoys may share a key; the  just currently don't), and that the former will soon be wrong, once the News Web team roll out [Ranged Decoys](https://stash.abc-dev.net.au/projects/PL/repos/pl/pull-requests/2060/overview).

For JavaScript apps which depend on this library, nothing needs to change, but TypeScript apps will complain if we try to call `requestDOMPermit` with a `key` that isn't a `DECOY_KEYS` enum value, because we typed it that way.

This PR will only affects usage of the library with TypeScript apps, and does the following:

- Relaxes the type restrictions on decoy key arguments from `DECOY_KEYS` enum values (effectively: `'article' | 'body' | 'page'`) to `string`.
- Retains the `DECOY_KEYS` enum as a list of known keys (that are provided by News Web), so we can continue using them, and avoiding breaking backwards-compatibility.
- Clarifies in the README that decoy keys can be any [a-z] string
- Clarifies in the README that multiple decoys may be activated as a result of a single `requestDOMPermit` call

### CODE REVIEW

**Review by drzax — APPROVED** [review]
Lets get this released.

**Review by drzax — CHANGES_REQUESTED** [review]
I was a little hasty on my approval. We may want to merge this anyway so we can start using it, but there will be a breaking change in the near future to support multiple activations using a single key.

Some assumptions we made about how PL processes activations and sends events about them was incorrect. If there are multiple decoys in the page with the same key, currently, individual events will be sent for each activation and we can't safely assume that the first event we receive with that key indicates all of them have been activated. 

Some PL changes will be required to resolve this. The plan at this point is to attach the DOM node which is subject of a `decoyActive` or `decoyInactive` event to the event itself. 

This will mean the listener shouldn't be detached since we don't (necessarily) know how many decoys will be activated for a single `decoy` request.

**Review by phocks — APPROVED** [review]
arbitrary strings! Yeah let's do it

**Comment by drzax** [comment]
There are two ways we could go with this. Now that I've written all this out, I'm leaning toward option 1, on balance, but would like your thoughts.

## Options

### 1. anticipate the number of expected permits for a request

This is the least disruptive option but it feels more fragile. It would mean for each permit request, we would first query the DOM for the number of nodes we would expect to be decoyed. Then after sending the `decoy` request event we'd need to wait until that number of `decoyActive` events (for the given key) are received *before* resolving the promise.

### 2. move away from the promise based interface

Because it will potentially receive an arbitrary number of `decoyActive` events from PL for a single `decoy` request event, to keep the promise interface, we'd need to anticipate how many we'll receive (as noted above). 

To avoid doing that we could move to a callback interface in which a single `requestDOMPermit` call would accept a `decoyActivatedHandler` function which is called once for every DOM node that gets activated. 

This has one advantage I can think of: It it means that if the anticipated number of decoy activations aren't received for whatever reason, we can proceed with some of them and wait on in hope with the ones that aren't.

## What gets returned?

In either scenario above, we can return (either via the promise resolution or the callback function) the DOM node(s) which are the subject of `decoyActive` events. The only trouble is that for non PL pages we'd have to translate the requested nodes to DOM nodes ourselves, based on our own rules (possibly requiring a `util-news-selectors` dependency). 

Or complicate the API by returning different things depending on the `GENERATION` in question (i.e. undefined for non-PL pages and DOM nodes for PL pages).

Again, I'd appreciate your thoughts on this.

**Comment by drzax** [comment]
Here's what option one, without any changes to return values, would look like: https://github.com/abcnews/env-utils/pull/11

**Comment by drzax** [comment]
@colingourlay apparently I can't assign you to review your own PR.

**Comment by drzax** [comment]
This has been updated to choose implement 1 from my comment above with a return value that differs between PL and prior generations. When `requestDOMPermit` is run on PL, the promise will resolve with an array of `HTMLElement` nodes which have been decoyed. Prior generations will immediately resolve to `true` in all circumstances.

**Review by phocks — APPROVED** [review]
Seems reasonable.

**Pull request merged**
